const dataDummy = [
    {
        nik: "1234567890",
        nama: "John Doe",
        posisi: "Manager",
        alamat: "Jl. Jalan No. 1",
        bandPosisi: "A1",
        noHandphone: "081234567",
        kotaPemasangan: "Jakarta",
        witelPemasangan: "Jakarta",
        noInternet: "1234567890",
        status: "-",
    },
    {
        nik: "1234567890",
        nama: "John Doe",
        posisi: "Manager",
        alamat: "Jl. Jalan No. 1",
        bandPosisi: "A1",
        noHandphone: "081234567",
        kotaPemasangan: "Jakarta",
        witelPemasangan: "Jakarta",
        noInternet: "1234567890",
        status: "-",
    },
    {
        nik: "1234567890",
        nama: "John Doe",
        posisi: "Manager",
        alamat: "Jl. Jalan No. 1",
        bandPosisi: "A1",
        noHandphone: "081234567",
        kotaPemasangan: "Jakarta",
        witelPemasangan: "Jakarta",
        noInternet: "1234567890",
        status: "-",
    },
    {
        nik: "1234567890",
        nama: "John Doe",
        posisi: "Manager",
        alamat: "Jl. Jalan No. 1",
        bandPosisi: "A1",
        noHandphone: "081234567",
        kotaPemasangan: "Jakarta",
        witelPemasangan: "Jakarta",
        noInternet: "1234567890",
        status: "-",
    },
    {
        nik: "1234567890",
        nama: "John Doe",
        posisi: "Manager",
        alamat: "Jl. Jalan No. 1",
        bandPosisi: "A1",
        noHandphone: "081234567",
        kotaPemasangan: "Jakarta",
        witelPemasangan: "Jakarta",
        noInternet: "1234567890",
        status: "-",
    },
];

export default dataDummy;
